name: CI - Snapshot
run-name: CI snapshot disparada por ${{ github.actor }}

on:   
  # inicia o workflow manualmente
  workflow_dispatch:
jobs:  
  build_back:
    name: Build Back
    runs-on: ubuntu-latest
    steps:
      - name: Baixando o repositório
        uses: actions/checkout@v4
        with:
          repository: ${{ github.repository }}
          path: build
      - name: Compila o(s) projeto(s)
        shell: bash
        run: |
          cd build/ci_cd_projeto/backend
          npm install
          npm run build
      - name: Compacta(Zip) buid
        shell: bash
        run: |
          cd build/ci_cd_projeto/backend
          zip -r backend.zip dist
      - name: Upload Zip Backend
        uses: actions/upload-artifact@v4
        with:
          name: backend
          path: build/ci_cd_projeto/backend/backend.zip



  build_front:
    name: Build Front
    runs-on: ubuntu-latest
    steps:
      - name: Baixando o repositório
        uses: actions/checkout@v4
        with:
          repository: ${{ github.repository }}
          path: build
      - name: Compila o(s) projeto(s)
        shell: bash
        run: |
          cd build/ci_cd_projeto/frontend
          npm install
          npm run build
      - name: Compacta(Zip) buid
        shell: bash
        run: |
          cd build/ci_cd_projeto/frontend
          zip -r frontend.zip dist
      - name: Upload Zip Frontend
        uses: actions/upload-artifact@v4
        with:
          name: frontend
          path: build/ci_cd_projeto/frontend/frontend.zip
         
  GerarVersao:
    runs-on: ubuntu-latest
    outputs:
      versao: ${{ steps.versao.outputs.versao }}
    steps:
      - name: Baixando o repositório
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Coleta última versão
        id: ultimatag
        uses: "WyriHaximus/github-action-get-previous-tag@v1"
        with:
          fallback: 1.0.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Número próximas versões
        id: versoes
        uses: "WyriHaximus/github-action-next-semvers@v1"
        with:
          version: ${{ steps.ultimatag.outputs.tag }}
      - name: Versão
        id: versao
        shell: sh
        run: |
          versao=$(
            case "${{ inputs.tipo_versao }}" in
              ("patch") echo "${{ steps.versoes.outputs.patch }}" ;;
              ("minor") echo "${{ steps.versoes.outputs.minor }}" ;;
              ("major") echo "${{ steps.versoes.outputs.major }}" ;;
              ("replace_last") echo "${{ steps.ultimatag.outputs.tag }}" ;;
              ("snapshot") echo "${{ steps.versoes.outputs.minor }}.${{github.ref_name }}.snapshot" ;;
              (*) echo "${{ steps.versoes.outputs.minor }}.snapshot" ;;
            esac)
          echo "--- Versões ---"
          echo "snapshot=${{ steps.versoes.outputs.minor }}.snapshot"
          echo "patch=${{ steps.versoes.outputs.patch }}"
          echo "minor=${{ steps.versoes.outputs.minor }}"
          echo "major=${{ steps.versoes.outputs.major }}"
          echo "replace_last=${{ steps.ultimatag.outputs.tag }}"
          echo "--- Versão escolhida ---"
          echo "versao=${versao}"
          echo "versao=${versao}" >> "$GITHUB_OUTPUT"
